### ISSUE TITLE
Cleaned Oscar dataset

### ISSUE THREAD

**Issue by kolakows** [Ermlab/PoLitBert#2]
Hello,

I am curious about the Cleaned Polish Oscar corpus. 

Are the linked corpus_oscar_2020-04-10*lines.txt files already cleaned versions, or should I run the process_sentences.py script on them? For what I understood, there are non-polish and invalid lenght sentences in these files?

Thanks in advance!

**Comment by lsawaniewski** [comment]
Hi @kolakows 
All linked files are parts of the Oscar Corpus **after** cleaning with `process_sentences.py` and removing incorrect and non-Polish sentences.
